---
- name: Setup Minecraft Server using Docker
  hosts: minecraft_project_2
  become: true

  tasks:
    - name: Install required packages
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - docker
        - git

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Pull Minecraft Docker image
      docker_image:
        name: itzg/minecraft-server
        source: pull

    - name: Run Minecraft container
      docker_container:
        name: minecraft
        image: itzg/minecraft-server
        state: started
        restart_policy: always
        ports:
          - "25565:25565"
        env:
          EULA: "TRUE"
          MEMORY: "2G"

